## index : An index is a special feature in SQL that helps the database find data faster.
create index idx_last_name
on customer(last_name);
select *
from customer
where last_name = 'smith';

create index idx_title
on film(title);
select *
from film
where title = 'academy dinosaur';

## ex : ecommerce - to find iphone16
select *
from products
where product_name = 'iphone 16';
## An index helps SQL search data quickly. It improves query performance by reducing the time taken to find records.
##faster data searching.Improves query performance.
##Reduces execution time.Reduces database cost because fewer resources are used.
##  con : Uses extra storage space. Inserts, updates, and deletes become slightly slower because the index also needs to be updated.

## clustered index : A clustered index stores the actual table data in the order of the indexed column.
## A table can have only one clustered index because data can only be stored in one order.
## PK = clustered index 
## describe customer; - customer_id   PRI
## You cannot manually create a clustered index in MySQL. It is automatically created for the primary key.
## con : Updating the clustered key can be expensive because rows may need to be reordered.

## non clustered index : A non-clustered index creates a separate list of indexed values and points to the actual table rows.
## It does not change the order of the data. can be many for a table 
create index idx_first_name
on customer(first_name);
##This creates an index on the first_name column.Now SQL can search customers by first name much faster.
select *
from customer
where email = 'mary.smith@sakilacustomer.org';
## The index is created on email. The table order does not change, but searching becomes faster.
## A non-clustered index stores the indexed values separately and points to the original data.
## faster search on non PK columns 
## Slows down insert, update, and delete operations.


## natural key : A natural key is a value that is already unique in the real world. ex : passport no 
## A natural key is a real-world value that is already unique.
## already exists in real world 
## Sometimes the value may change (for example, an email address).May be long or difficult to use as a primary key.


## surrogate key :it is generated by the database or system.
## Usually, it is an auto-increment integer.\
customer_id   first_name

1             John
2             Mary
3             David
## customer_id is a surrogate key because the database generated it.
create table customer(
customer_id int auto_increment primary key,
first_name varchar(50)
);
select * from customer ;
## A surrogate key is a system-generated unique ID used as the primary key.
## Never changes.Always unique.Easy to use in joins.
## Has no real-world meaning.Requires an additional column.

## ***  Check Query Execution Plan :
explain
select *
from customer
where last_name = 'smith';
## explain shows how MySQL executes the query and whether it is using an index.




select database();
use sakila;

